### ISSUE TITLE
Duplicate rules aren't removed at all

### ISSUE THREAD

**Issue by gsklee** [adamjgrant/gulp-css-purge#1]
I have a file that looked like this:

``` css
.left {
    float: left !important;
}
.right {
    float: right !important;
}
.left {
    float: left !important;
}
.right {
    float: right !important;
}
```

Using `gulp-css-purge` generate this output:

``` css
.left {
    float: left !important;
    float: left !important;
}
.right {
    float: right !important;
    float: right !important;
}
```

While the selectors were combined, the rules are not.
